---
abstract: 'Digest authentication'
author:
  - 'Yuji Shimada <xaicron@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Auth-Digest
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Digest::HMAC_SHA1: 0
  Digest::MD5: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Plack: 0
  Test::More: 0.88
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/miyagawa/Plack-Middleware-Auth-Digest.git
version: 0.03_01
